---
title: "2019 SWMP for SSAM-1"
author: "Shannon Dunnigan"
date: "2020-05-21 (updated: `r Sys.Date()`)"
output: 
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(dpi = 120)
knitr::opts_chunk$set(fig.align = "center")
source(here::here('R', '00_loadpackages.R')) # load package libraries----
source(here::here('R', 'veg', '00_visuals.R')) # load defined visual palettes----
source(here::here('R', 'veg', '01_load.R')) # load vegetation data----
source(here::here('R', 'veg', '02_wrangle_tidy.R')) # wrangle and tidy veg data----
```

# Characterization of all sites 

Examining percent cover of all data collected 2012-2019

*will still need to transpose with a map, but best to do so in PowerPoint*

```{r percentcover-allsites-allyears, echo = FALSE, fig.height = 8, fig.width = 4}
# percent cover plot for all sites
# average all plots together for all years and all seasons
dat_veg_all %>%
  dplyr::group_by(site_name, species) %>%
  dplyr::summarise(mean_pc = mean(percent_cover, na.rm = TRUE)) %>%
  ggplot() +
  geom_bar(aes(x = "", y = mean_pc, fill = species), 
           color = "white", 
           width = 1, 
           stat = "identity",
           position = "fill") + # by setting position = "fill" this will fill up any gaps caused by averaging percent cover measurements
  coord_polar("y", start = 0) +
  facet_grid(site_name ~.,) + # reverse these to flip it vertical
  scale_fill_manual(name = "Species",
                    values = speciescolours_all, 
                    labels = expression(italic('Avicennia germinans'), # this allows you to have italicized species names in legend, but not italicize Unvegetated
                                        italic('Batis maritima'),
                                        italic('Distichlis spicata'),
                                        italic('Juncus roemerianus'),
                                        italic('Salicornia ambigua'),
                                        italic('Spartina alterniflora'),
                                        'Unvegetated')
                    ) +
  theme_void() +
  theme(legend.position = "right",
        legend.text.align = 0) # align species names in legend to the left

```

# 2019

```{r percentcover-2019vspast, echo = FALSE, fig.height = 8, fig.width = 5}
dat_veg_all %>%
  dplyr::mutate(interestYR = ifelse(year < 2019, "2012-2018", "2019")) %>%
  dplyr::group_by(interestYR, site_name, species) %>%
  dplyr::summarise(mean_pc = mean(percent_cover, na.rm = TRUE)) %>%
  ggplot() +
  geom_bar(aes(x = "", y = mean_pc, fill = species), 
           color = "white", 
           width = 1, 
           stat = "identity",
           position = "fill") +
  coord_polar("y", start = 0) +
  facet_grid(site_name ~ interestYR) + 
  scale_fill_manual(name = "Species",
                    values = speciescolours_all, 
                    labels = expression(italic('Avicennia germinans'), # this allows you to have italicized species names in legend, but not italicize Unvegetated
                                        italic('Batis maritima'),
                                        italic('Distichlis spicata'),
                                        italic('Juncus roemerianus'),
                                        italic('Salicornia ambigua'),
                                        italic('Spartina alterniflora'),
                                        'Unvegetated')
                    ) +
  theme_void() +
  theme(legend.position = "right",
        legend.text.align = 0) # align species names in legend to the left 
```



```{r percentcover-season-year-function, include = FALSE}
pct_cov_2019vs <- function(season_int) {

dat_veg_all %>%
  dplyr::mutate(interestYR = ifelse(year < 2019, "2012-2018", "2019")) %>%
  dplyr::filter(season == season_int) %>%
  dplyr::group_by(interestYR, site_name, species) %>%
  dplyr::summarise(mean_pc = mean(percent_cover, na.rm = TRUE)) %>%
  ggplot() +
  geom_bar(aes(x = "", y = mean_pc, fill = species), 
           color = "white", 
           width = 1, 
           stat = "identity",
           position = "fill") +
  coord_polar("y", start = 0) +
  facet_grid(interestYR ~ site_name) + 
    scale_fill_manual(name = "Species",
                      values = speciescolours_all, 
                      labels = expression(italic('Avicennia germinans'), # this allows you to have italicized species names in legend, but not italicize Unvegetated
                                          italic('Batis maritima'),
                                          italic('Distichlis spicata'),
                                          italic('Juncus roemerianus'),
                                          italic('Salicornia ambigua'),
                                          italic('Spartina alterniflora'),
                                          'Unvegetated')
    ) +
  theme_void() +
  theme(legend.position = "top",
        legend.text.align = 0) +
  labs(title = paste(season_int, "Season"))

}
```

## Spring

```{r percent-cover-spring-year, echo = FALSE, fig.width = 8, fig.height = 4}
pct_cov_2019vs(season_int = "Spring")
```

# Fall

```{r percent-cover-fall-year, echo = FALSE, fig.width = 8, fig.height = 4}
pct_cov_2019vs(season_int = "Fall")
```